@baseUrl = http://localhost:8080/api

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

###

POST {{baseUrl}}/auth/activate?token=activation-token

###

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###

GET {{baseUrl}}/auth/me

###

POST {{baseUrl}}/auth/logout

###

POST {{baseUrl}}/auth/reset-password/request
Content-Type: application/json

{
  "email": "john.doe@example.com"
}

###

POST {{baseUrl}}/auth/reset-password/confirm?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODRkY2U4OWFlYTRjNjIzZjI0MjdhOGIiLCJ0eXBlIjoicGFzc3dvcmQiLCJpYXQiOjE3NTAxNzA4MTYsImV4cCI6MTc1MDE3MTcxNn0.PwFbGIOIKFUVwwPHNKguVPPRJ0MCmEMCf9amKYEV-G8
Content-Type: application/json

{
  "newPassword": "newpassword123"
}